-- ============================================================
-- 071_audit_log
-- Защищённый audit-log: schema `audit` (изолирована от PostgREST),
-- партиционирование по месяцам, generic-триггер на mutating-таблицы,
-- RPC log_event для прикладных событий.
--
-- Категории:
--   auth     — signin/signout/password_reset/email_change/...
--   admin    — role_changed/student_deleted/teacher_approved/...
--   payment  — payment_created/webhook_*/refund/...
--   data     — auto-generated rows from trg_data_change()
--
-- Изоляция:
--   - schema `audit` НЕ exposed через PostgREST (REVOKE USAGE FROM anon, authenticated)
--   - RLS на audit_log: SELECT только admin, INSERT/UPDATE/DELETE — никому
--   - log_event = SECURITY DEFINER + search_path locked → пишет от owner-а
-- ============================================================

CREATE SCHEMA IF NOT EXISTS audit;

-- PostgREST exposes only public/storage/graphql by default, но на всякий
-- явно отзовём USAGE у клиентских ролей.
REVOKE ALL ON SCHEMA audit FROM PUBLIC;
REVOKE ALL ON SCHEMA audit FROM anon, authenticated;
-- service_role и postgres сохраняют доступ через GRANT ALL ниже.
GRANT USAGE ON SCHEMA audit TO postgres, service_role;

-- ============================================================
-- 1. Партиционированная таблица audit_log (RANGE by created_at)
-- ============================================================

CREATE TABLE IF NOT EXISTS audit.audit_log (
  id              bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at      timestamptz NOT NULL DEFAULT now(),
  actor_user_id   uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  actor_role      text,
  actor_ip        inet,
  actor_user_agent text,
  category        text NOT NULL CHECK (category IN ('auth','admin','payment','data')),
  action          text NOT NULL,
  target_type     text,
  target_id       text,
  payload         jsonb,
  request_id      text,
  -- PK обязан включать ключ партиционирования.
  PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

COMMENT ON TABLE audit.audit_log IS
  'Append-only audit log. Writes ONLY via SECURITY DEFINER (log_event/trg_data_change). Partitioned monthly.';

CREATE INDEX IF NOT EXISTS audit_log_actor_created_idx
  ON audit.audit_log (actor_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS audit_log_category_created_idx
  ON audit.audit_log (category, created_at DESC);

CREATE INDEX IF NOT EXISTS audit_log_target_created_idx
  ON audit.audit_log (target_type, target_id, created_at DESC);

-- ============================================================
-- 2. Партиции + ensure_partitions() — idempotent, 3 мес вперёд
-- ============================================================

CREATE OR REPLACE FUNCTION audit.ensure_partitions()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_month_start date;
  v_next_month  date;
  v_part_name   text;
  v_i           int;
BEGIN
  -- Создаём текущий + 3 будущих месяца + предыдущий (на случай drift'а часов).
  FOR v_i IN -1..3 LOOP
    v_month_start := date_trunc('month', now() + (v_i || ' months')::interval)::date;
    v_next_month  := (v_month_start + interval '1 month')::date;
    v_part_name   := format('audit_log_%s', to_char(v_month_start, 'YYYYMM'));

    IF NOT EXISTS (
      SELECT 1 FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = 'audit' AND c.relname = v_part_name
    ) THEN
      EXECUTE format(
        'CREATE TABLE audit.%I PARTITION OF audit.audit_log FOR VALUES FROM (%L) TO (%L)',
        v_part_name, v_month_start, v_next_month
      );
    END IF;
  END LOOP;
END;
$$;

REVOKE ALL ON FUNCTION audit.ensure_partitions() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION audit.ensure_partitions() TO postgres, service_role;

-- Materialise partitions для текущей даты + future.
SELECT audit.ensure_partitions();

-- Default-партиция — ловит вставки, если ensure_partitions() забудет запуститься.
-- Лучше «куча в default» чем INSERT-ошибка в проде.
CREATE TABLE IF NOT EXISTS audit.audit_log_default
  PARTITION OF audit.audit_log DEFAULT;

-- ============================================================
-- 3. RLS — read-only для admin, никаких прямых пишущих операций
-- ============================================================

ALTER TABLE audit.audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit.audit_log FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS audit_log_select_admin ON audit.audit_log;
CREATE POLICY audit_log_select_admin ON audit.audit_log
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles p
      WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

-- Никаких INSERT/UPDATE/DELETE-политик нет → отказ по умолчанию.

-- ============================================================
-- 4. RPC log_event — единственная точка записи прикладных событий
-- ============================================================

CREATE OR REPLACE FUNCTION audit.log_event(
  p_category      text,
  p_action        text,
  p_target_type   text DEFAULT NULL,
  p_target_id     text DEFAULT NULL,
  p_payload       jsonb DEFAULT NULL,
  p_ip            inet  DEFAULT NULL,
  p_user_agent    text  DEFAULT NULL,
  p_request_id    text  DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, audit
AS $$
DECLARE
  v_uid  uuid;
  v_role text;
  v_id   bigint;
BEGIN
  IF p_category NOT IN ('auth','admin','payment','data') THEN
    RAISE EXCEPTION 'audit.log_event: invalid category %', p_category
      USING ERRCODE = '22023';
  END IF;
  IF p_action IS NULL OR length(btrim(p_action)) = 0 THEN
    RAISE EXCEPTION 'audit.log_event: action must be non-empty'
      USING ERRCODE = '22023';
  END IF;

  v_uid := auth.uid();

  IF v_uid IS NOT NULL THEN
    SELECT role INTO v_role FROM public.profiles WHERE id = v_uid;
  END IF;

  INSERT INTO audit.audit_log (
    actor_user_id, actor_role, actor_ip, actor_user_agent,
    category, action, target_type, target_id,
    payload, request_id
  )
  VALUES (
    v_uid, v_role, p_ip, p_user_agent,
    p_category, p_action, p_target_type, p_target_id,
    p_payload, p_request_id
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION audit.log_event(text, text, text, text, jsonb, inet, text, text) FROM PUBLIC;
-- Доступно только service_role (TS-helper через createAdminClient).
GRANT EXECUTE ON FUNCTION audit.log_event(text, text, text, text, jsonb, inet, text, text)
  TO service_role;

-- Чтобы supabase-js увидел RPC через PostgREST, делаем proxy в public.
-- public.audit_log_event(...) → audit.log_event(...). Только service_role.
CREATE OR REPLACE FUNCTION public.audit_log_event(
  p_category      text,
  p_action        text,
  p_target_type   text DEFAULT NULL,
  p_target_id     text DEFAULT NULL,
  p_payload       jsonb DEFAULT NULL,
  p_ip            inet  DEFAULT NULL,
  p_user_agent    text  DEFAULT NULL,
  p_request_id    text  DEFAULT NULL
)
RETURNS bigint
LANGUAGE sql
SECURITY DEFINER
SET search_path = pg_catalog, audit, public
AS $$
  SELECT audit.log_event(
    p_category, p_action, p_target_type, p_target_id,
    p_payload, p_ip, p_user_agent, p_request_id
  );
$$;

-- Default Supabase grants отдают EXECUTE на public-функции anon+authenticated.
-- Закрываем явно — только service_role может звать RPC.
REVOKE EXECUTE ON FUNCTION public.audit_log_event(text, text, text, text, jsonb, inet, text, text)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.audit_log_event(text, text, text, text, jsonb, inet, text, text)
  TO service_role;

-- ============================================================
-- 5. Generic-триггер trg_data_change → category='data'
-- ============================================================

CREATE OR REPLACE FUNCTION audit.trg_data_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, audit
AS $$
DECLARE
  v_uid           uuid;
  v_role          text;
  v_old           jsonb;
  v_new           jsonb;
  v_changed_cols  text[];
  v_target_id     text;
  v_target_type   text;
  v_payload       jsonb;
BEGIN
  v_uid  := auth.uid();
  IF v_uid IS NOT NULL THEN
    SELECT role INTO v_role FROM public.profiles WHERE id = v_uid;
  END IF;

  v_target_type := TG_TABLE_SCHEMA || '.' || TG_TABLE_NAME;

  IF TG_OP = 'INSERT' THEN
    v_new       := to_jsonb(NEW);
    v_old       := NULL;
    v_target_id := COALESCE((v_new ->> 'id'), NULL);
  ELSIF TG_OP = 'UPDATE' THEN
    v_old := to_jsonb(OLD);
    v_new := to_jsonb(NEW);
    SELECT COALESCE(array_agg(key), '{}')
      INTO v_changed_cols
      FROM jsonb_each(v_new)
     WHERE v_old -> key IS DISTINCT FROM v_new -> key;
    -- Не пишем noop-апдейты (часто триггерятся moddatetime / RLS no-op).
    IF v_changed_cols IS NULL OR array_length(v_changed_cols, 1) IS NULL THEN
      RETURN NULL;
    END IF;
    v_target_id := COALESCE((v_new ->> 'id'), NULL);
  ELSIF TG_OP = 'DELETE' THEN
    v_old       := to_jsonb(OLD);
    v_new       := NULL;
    v_target_id := COALESCE((v_old ->> 'id'), NULL);
  END IF;

  -- Сжатие: для UPDATE кладём только изменившиеся поля, чтобы лог не пух.
  IF TG_OP = 'UPDATE' THEN
    v_payload := jsonb_build_object(
      'op', TG_OP,
      'changed_cols', to_jsonb(v_changed_cols),
      'old_row', (
        SELECT jsonb_object_agg(key, v_old -> key)
        FROM unnest(v_changed_cols) AS key
      ),
      'new_row', (
        SELECT jsonb_object_agg(key, v_new -> key)
        FROM unnest(v_changed_cols) AS key
      )
    );
  ELSE
    v_payload := jsonb_build_object(
      'op', TG_OP,
      'old_row', v_old,
      'new_row', v_new
    );
  END IF;

  INSERT INTO audit.audit_log (
    actor_user_id, actor_role, category, action,
    target_type, target_id, payload
  )
  VALUES (
    v_uid, v_role, 'data', lower(TG_OP),
    v_target_type, v_target_id, v_payload
  );

  RETURN NULL;  -- AFTER-trigger, return value игнорируется.
END;
$$;

REVOKE ALL ON FUNCTION audit.trg_data_change() FROM PUBLIC, anon, authenticated;
-- Триггер вызывается системой; явный GRANT не нужен (SECURITY DEFINER).

-- Подключаем к 4 базовым таблицам.
DROP TRIGGER IF EXISTS audit_profiles_change ON public.profiles;
CREATE TRIGGER audit_profiles_change
  AFTER INSERT OR UPDATE OR DELETE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION audit.trg_data_change();

DROP TRIGGER IF EXISTS audit_lessons_change ON public.lessons;
CREATE TRIGGER audit_lessons_change
  AFTER INSERT OR UPDATE OR DELETE ON public.lessons
  FOR EACH ROW EXECUTE FUNCTION audit.trg_data_change();

DROP TRIGGER IF EXISTS audit_payments_change ON public.payments;
CREATE TRIGGER audit_payments_change
  AFTER INSERT OR UPDATE OR DELETE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION audit.trg_data_change();

DROP TRIGGER IF EXISTS audit_materials_change ON public.materials;
CREATE TRIGGER audit_materials_change
  AFTER INSERT OR UPDATE OR DELETE ON public.materials
  FOR EACH ROW EXECUTE FUNCTION audit.trg_data_change();

-- ============================================================
-- 6. pg_cron: 1-го числа каждого месяца provision next partition
-- ============================================================

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    -- Снимем дубль (idempotent re-run миграции).
    PERFORM cron.unschedule('audit_ensure_partitions')
      WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'audit_ensure_partitions');

    PERFORM cron.schedule(
      'audit_ensure_partitions',
      '0 3 1 * *',                        -- 03:00 UTC, 1-го числа
      $cron$ SELECT audit.ensure_partitions(); $cron$
    );
  END IF;
END
$$;
